import Link from "next/link";
import { Brain, Target, TrendingUp, Zap, ChevronRight, CheckCircle } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    desc: "Questions generated by a local Llama model — fresh, relevant, and aligned with real placement patterns.",
  },
  {
    icon: Target,
    title: "4 Test Categories",
    desc: "Aptitude, Verbal, Technical, and Coding — everything you need to crack TCS, Infosys, Wipro, Amazon, and more.",
  },
  {
    icon: TrendingUp,
    title: "Deep Analytics",
    desc: "Track your progress with category-wise scores, radar charts, and streak calendars.",
  },
  {
    icon: Zap,
    title: "AI Tutor",
    desc: "Stuck on a concept? Ask the AI tutor anything — it explains concepts, solves doubts, and reviews your code.",
  },
];

const companies = ["TCS", "Infosys", "Wipro", "Cognizant", "Amazon", "Google", "Accenture", "HCL"];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 border-b border-border/40 bg-white/80 backdrop-blur-sm">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2 font-bold text-xl text-primary">
            <Brain className="h-6 w-6" />
            PlacementPrep
          </div>
          <div className="flex items-center gap-4">
            <Link
              href="/login"
              className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              Sign in
            </Link>
            <Link
              href="/register"
              className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
            >
              Get started free
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="mx-auto max-w-6xl px-6 py-24 text-center">
        <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary mb-8">
          <Zap className="h-3.5 w-3.5" />
          Powered by local Llama AI — your data stays private
        </div>
        <h1 className="text-5xl font-bold tracking-tight text-foreground sm:text-6xl">
          Crack your campus
          <br />
          <span className="text-primary">placement tests</span>
        </h1>
        <p className="mt-6 text-lg text-muted-foreground max-w-2xl mx-auto">
          Practice with AI-generated questions, get instant explanations, and track your progress
          with smart analytics. Built for engineering students, by engineers.
        </p>
        <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link
            href="/register"
            className="inline-flex items-center gap-2 rounded-xl bg-primary px-8 py-3.5 text-base font-semibold text-primary-foreground hover:bg-primary/90 transition-colors shadow-lg shadow-primary/25"
          >
            Start practicing for free
            <ChevronRight className="h-4 w-4" />
          </Link>
          <Link
            href="/login"
            className="inline-flex items-center gap-2 rounded-xl border border-border px-8 py-3.5 text-base font-semibold text-foreground hover:bg-muted transition-colors"
          >
            Sign in
          </Link>
        </div>
      </section>

      {/* Companies */}
      <section className="border-y border-border bg-white/50 py-10">
        <div className="mx-auto max-w-6xl px-6">
          <p className="text-center text-sm text-muted-foreground mb-6">
            Preparation aligned with top company patterns
          </p>
          <div className="flex flex-wrap justify-center gap-8">
            {companies.map((c) => (
              <span key={c} className="text-lg font-bold text-muted-foreground/60">
                {c}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-6xl px-6 py-24">
        <h2 className="text-3xl font-bold text-center text-foreground mb-16">
          Everything you need to prepare
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
          {features.map(({ icon: Icon, title, desc }) => (
            <div
              key={title}
              className="rounded-2xl border border-border bg-white p-8 hover:shadow-md transition-shadow"
            >
              <div className="mb-4 inline-flex rounded-xl bg-primary/10 p-3">
                <Icon className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-xl font-semibold text-foreground mb-2">{title}</h3>
              <p className="text-muted-foreground">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-6xl px-6 pb-24">
        <div className="rounded-3xl bg-primary px-8 py-16 text-center text-white">
          <h2 className="text-3xl font-bold mb-4">Ready to start your placement prep?</h2>
          <p className="text-primary-foreground/80 mb-8 max-w-md mx-auto">
            Join thousands of engineering students practicing smart with AI.
          </p>
          <Link
            href="/register"
            className="inline-flex items-center gap-2 rounded-xl bg-white px-8 py-3.5 text-base font-semibold text-primary hover:bg-white/90 transition-colors"
          >
            Create free account
            <ChevronRight className="h-4 w-4" />
          </Link>
          <div className="mt-8 flex items-center justify-center gap-6 text-sm text-primary-foreground/70">
            {["No credit card", "Unlimited practice", "AI explanations"].map((t) => (
              <div key={t} className="flex items-center gap-1.5">
                <CheckCircle className="h-4 w-4" />
                {t}
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
